### ISSUE TITLE
Context loss in '<For>', 'this' in undefined

### ISSUE THREAD

**Issue by alex-shamshurin** [AlexGilleran/jsx-control-statements#66] opened 2017-07-14 15:47 UTC
Consider this component
```
 <Choose>
        <When condition={tripsData.trips.length > 0}>
         {console.log('this', this)} //this is OK
          <For each="trip" of={tripsData.trips}>
            {console.log('this', this)} //this is lost here
            <Collapse isOpened key={`collapsed_ ${trip.id}`}>
              <div className={cx('trip-container')}>
                <Choose>
                  <When condition={trip.isOpen}>
                    <ExpandedTrip
                      cx={cx}
                      id={trip.id}
                      trip={trip}
                      isDebug={isDebug}
                      ticketCount={ticketCount}
                      onSelectSeat={this.onSelectSeat}
                      onTripClose={this.onTripClose}
                      firstStepActions={firstStepActions}
                      secondStepActions={secondStepActions}
                      buttonIsSpinning={buttonIsSpinning}
                    />
                  </When>
                  <Otherwise>
                    <CollapsedTrip
                      cx={cx}
                      id={trip.id}
                      isDebug={isDebug}
                      trip={trip}
                      onTripClick={this.onTripClick}
                    />
                  </Otherwise>
                </Choose>
              </div>
            </Collapse>,
          </For>
        </When>
        <Otherwise>
          <div className={cx('trip')}>
            Not found
          </div>
        </Otherwise>
      </Choose>

```

In second `console.log` context is lost.

**Comment by texttechne** [comment] 2017-07-16 22:26
Actually I cannot reproduce this context loss.

So your problem is, that this part (for example) does not work, because `this` doesn't refer properly?
```
<ExpandedTrip
  ....
  onSelectSeat={this.onSelectSeat}
  onTripClose={this.onTripClose}
  ...
/>
```
What's the exact error message? How does the rest of your component look like?

**Comment by alex-shamshurin** [comment] 2017-07-17 06:28
Yes, `this` is null everywhere when I use `For`. 

This works perfectly:

```
 <Choose>
        <When condition={tripsData.trips.length > 0}>
          {tripsData.trips.map(trip =>
            <Collapse isOpened key={`collapsed_ ${trip.id}`}>
              <div className={cx('trip-container')}>
                <Choose>
                  <When condition={trip.isOpen}>
                    <ExpandedTrip
                      cx={cx}
                      id={trip.id}
                      trip={trip}
                      isDebug={isDebug}
                      ticketCount={ticketCount}
                      onSelectSeat={this.onSelectSeat}
                      onTripClose={this.onTripClose}
                      firstStepActions={firstStepActions}
                      secondStepActions={secondStepActions}
                      buttonIsSpinning={buttonIsSpinning}
                    />
                  </When>
                  <Otherwise>
                    <CollapsedTrip
                      cx={cx}
                      id={trip.id}
                      isDebug={isDebug}
                      trip={trip}
                      onTripClick={this.onTripClick}
                    />
                  </Otherwise>
                </Choose>
              </div>
            </Collapse>,
          )}
        </When>
        <Otherwise>
          <div className={cx('trip')}>
            Not found
          </div>
        </Otherwise>
      </Choose>

```

**Comment by alex-shamshurin** [comment] 2017-07-17 06:29
Error is smth like `cannot get method onTripClick on undefined`

**Comment by texttechne** [comment] 2017-07-17 19:38
Sorry, I need more information to help. As I said, in my tests this works. And so far you're the only one experiencing this issue. So please do the following:

1) Create a minimal example to reproduce this issue
2) Provide the complete component

Thanks

**Comment by texttechne** [comment] 2017-07-24 08:34
@alex-shamshurin any updates?

**Comment by alex-shamshurin** [comment] 2017-07-24 08:44
Oh, sorry, I forgot. I will do it.

**Comment by texttechne** [comment] 2017-08-31 22:01
Closing this issue since it cannot be reproduced an no further feedback was given.

**Closed by texttechne** 2017-08-31 22:01 UTC
